### ISSUE TITLE
Multi-window multi-rate error budget burns

### ISSUE THREAD

**Issue by aditya-konarde** [metalmatze/slo-libsonnet#13]
Tracker to look at this and get those as default generated rules. 

@beorn7 showed us a really nice example of this during the meetup. 

ToDo: Also get the slides from beorn and see if we can post them on the repo as a representation of how the default generated alerts here are better than the basic ones that people usually go for.

**Comment by beorn7** [comment]
I think the best read in this regard is really chapter 5 of “The SRE Workbook”: https://landing.google.com/sre/workbook/chapters/alerting-on-slos/

After that, I'd recommend the blog post: https://developers.soundcloud.com/blog/alerting-on-slos

The slides are probably the worst as a reference and contain little what the other two don't. But if you really want to look at them: https://docs.google.com/presentation/d/17C8U5n15g1OpWy4OO07TqEhlFm66KokIz_LPNAjz4Vg/edit?usp=sharing

**Comment by metalmatze** [comment]
Yes. 👍 
As preparation for your talk I re-read that chapter and also your blog post, we should be able to get a lot of learnings out of them. 😊
Before we begin adding this to the library, we should have an example (or real) use case, which we can work on.

**Comment by aditya-konarde** [comment]
I think we're good to mark this as done, thanks to the awesome work by @metalmatze :confetti_ball:

**Comment by metalmatze** [comment]
I'll create a PR with some recent changes I've made yesterday. Once that's merged we can close this.

**Comment by metalmatze** [comment]
Nevermind. This can be closed indeed.
